security:

    providers:
        ministerio_user_bridge_user:
            id: ministerio_user_bridge.user_provider

    firewalls:

        ministerio_user_bridge_secured:
            pattern:   ^/
            stateless: false
            ministerio_user_bridge:  true
            form_login:
              login_path: /login
            logout:
              path:   /logout
              target: /
              invalidate_session: true

    access_control:
        - { path: ^/, roles: ROLE_ACCESS }